"use client"

import * as React from "react"
import type { WatchComment } from "@workspace/core/types"
import { ChevronDown, ChevronUp, Flag, ListFilter, Pin, Send, ThumbsDown, ThumbsUp } from "lucide-react"
import { useTranslations } from "next-intl"
import { useWatchComments } from "@/hooks/use-watch-comments"

export function WatchComments({ videoId, initialComments, initialNextCursor, locale }: { videoId: string; initialComments: WatchComment[]; initialNextCursor: string | null; locale: string }) {
  const t = useTranslations("video")
  const commentsPage = useWatchComments(videoId, initialComments, initialNextCursor)
  const comments = commentsPage.items
  const [draft, setDraft] = React.useState("")
  const [sort, setSort] = React.useState<"top" | "newest">("top")
  const [replyTo, setReplyTo] = React.useState<string | null>(null)
  const [replyDraft, setReplyDraft] = React.useState("")
  const [openReplies, setOpenReplies] = React.useState<Set<string>>(new Set(initialComments.map((item) => item.id)))
  const [reactions, setReactions] = React.useState<Record<string, "like" | "dislike">>({})

  const visible = [...comments].sort((left, right) => sort === "top" ? right.likeCount - left.likeCount : Date.parse(right.publishedAt) - Date.parse(left.publishedAt))
  function addComment() { if (!draft.trim()) return; commentsPage.prepend({ id: `comment-${Date.now()}`, author: t("you"), initials: "ME", message: draft.trim(), likeCount: 0, publishedAt: new Date().toISOString() }); setDraft("") }
  function addReply(parentId: string) { if (!replyDraft.trim()) return; commentsPage.updateItems((items) => items.map((item) => item.id === parentId ? { ...item, replies: [...(item.replies ?? []), { id: `reply-${Date.now()}`, author: t("you"), initials: "ME", message: replyDraft.trim(), likeCount: 0, publishedAt: new Date().toISOString() }] } : item)); setReplyDraft(""); setReplyTo(null) }

  return <section className="mt-8">
    <div className="flex items-center gap-4"><h2 className="text-lg font-bold">{t("comments", { count: comments.length })}</h2><button type="button" onClick={() => setSort((value) => value === "top" ? "newest" : "top")} className="flex items-center gap-2 rounded-full px-3 py-2 text-sm font-semibold hover:bg-muted"><ListFilter className="size-4" />{t(sort === "top" ? "sortTop" : "sortNewest")}</button></div>
    <div className="mt-5 flex gap-3"><span className="flex size-9 shrink-0 items-center justify-center rounded-full bg-foreground text-xs font-bold text-background">ME</span><div className="flex-1"><textarea value={draft} onChange={(event) => setDraft(event.target.value)} placeholder={t("addComment")} rows={1} className="w-full resize-none border-b bg-transparent px-1 py-2 text-sm outline-none focus:border-primary" /><div className="mt-2 flex justify-end gap-2"><button type="button" onClick={() => setDraft("")} className="rounded-full px-4 py-2 text-sm hover:bg-muted">{t("cancel")}</button><button type="button" disabled={!draft.trim()} onClick={addComment} className="flex items-center gap-2 rounded-full bg-primary px-4 py-2 text-sm text-primary-foreground disabled:opacity-50"><Send className="size-4" />{t("comment")}</button></div></div></div>
      <div className="mt-7 space-y-7">{visible.map((comment) => <article key={comment.id} className="flex gap-3"><span className="flex size-9 shrink-0 items-center justify-center rounded-full bg-muted text-xs font-bold">{comment.initials}</span><div className="min-w-0 flex-1">{comment.pinned ? <p className="mb-1 flex items-center gap-1 text-xs text-muted-foreground"><Pin className="size-3" />{t("pinned")}</p> : null}<p className="text-xs"><strong>{comment.author}</strong> <span className="text-muted-foreground">{new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeZone: "Asia/Bangkok" }).format(new Date(comment.publishedAt))}</span></p><p className="mt-1 text-sm leading-6">{comment.message}</p><div className="mt-1 flex items-center gap-1 text-xs"><button type="button" onClick={() => setReactions((items) => ({ ...items, [comment.id]: items[comment.id] === "like" ? undefined! : "like" }))} className="flex items-center gap-1 rounded-full px-2 py-1.5 hover:bg-muted"><ThumbsUp className={`size-3.5 ${reactions[comment.id] === "like" ? "fill-current text-primary" : ""}`} />{comment.likeCount + (reactions[comment.id] === "like" ? 1 : 0)}</button><button type="button" onClick={() => setReactions((items) => ({ ...items, [comment.id]: items[comment.id] === "dislike" ? undefined! : "dislike" }))} className="rounded-full p-2 hover:bg-muted"><ThumbsDown className={`size-3.5 ${reactions[comment.id] === "dislike" ? "fill-current" : ""}`} /></button><button type="button" onClick={() => setReplyTo(comment.id)} className="rounded-full px-3 py-1.5 font-semibold hover:bg-muted">{t("reply")}</button><button type="button" title={t("report")} className="rounded-full p-2 hover:bg-muted"><Flag className="size-3.5" /></button></div>
      {replyTo === comment.id ? <div className="mt-2 flex gap-2"><input autoFocus value={replyDraft} onChange={(event) => setReplyDraft(event.target.value)} placeholder={t("replyTo", { name: comment.author })} className="min-w-0 flex-1 border-b bg-transparent px-2 text-sm outline-none" /><button type="button" onClick={() => addReply(comment.id)} className="rounded-full bg-primary px-3 py-1.5 text-xs text-primary-foreground">{t("reply")}</button></div> : null}
      {(comment.replies?.length ?? 0) > 0 ? <div className="mt-2"><button type="button" onClick={() => setOpenReplies((current) => { const next = new Set(current); if (next.has(comment.id)) next.delete(comment.id); else next.add(comment.id); return next })} className="flex items-center gap-2 rounded-full px-3 py-2 text-sm font-semibold text-primary hover:bg-primary/10">{openReplies.has(comment.id) ? <ChevronUp className="size-4" /> : <ChevronDown className="size-4" />}{t("replies", { count: comment.replies!.length })}</button>{openReplies.has(comment.id) ? <div className="mt-2 space-y-4">{comment.replies!.map((reply) => <div key={reply.id} className="flex gap-2"><span className="flex size-7 shrink-0 items-center justify-center rounded-full bg-muted text-[10px] font-bold">{reply.initials}</span><div><p className="text-xs font-semibold">{reply.author}</p><p className="text-sm">{reply.message}</p></div></div>)}</div> : null}</div> : null}</div></article>)}</div>
    {commentsPage.hasMore ? <button type="button" disabled={commentsPage.loading} onClick={() => void commentsPage.loadMore()} className="mt-7 rounded-full border px-5 py-2.5 text-sm font-semibold hover:bg-muted disabled:opacity-60">{t(commentsPage.loading ? "loadingMore" : commentsPage.error ? "retry" : "loadMoreComments")}</button> : <p className="mt-7 text-sm text-muted-foreground">{t("allCommentsLoaded")}</p>}
  </section>
}
