export const viewerRoutes = {
  home: "/",
  shorts: "/shorts",
  trending: "/trending",
  following: "/following",
  library: "/library",
  history: "/history",
  watchLater: "/watch-later",
  liked: "/liked",
  search: "/search",
  upload: "/upload",
  watch: (videoId: string) => `/watch/${videoId}`,
  short: (videoId: string) => `/shorts/${videoId}`,
  playlist: (playlistId: string) => `/playlist/${playlistId}`,
  channel: (handle: string) => `/channel/${handle.replace(/^@/, "")}`,
  actor: (handle: string) => `/channel/${handle.replace(/^@/, "")}`,
  followedProfile: (_type: "actor" | "studio", handle: string) => `/channel/${handle.replace(/^@/, "")}`,
  studio: "/studio",
} as const
